### PR TITLE
SPM Support

### LINKED ISSUE #1: Migrate to SPM
Given the rising popularity of SPM, it would make sense to migrate this project to be a Swift package. CocoaPods will still work if the `s.source_files` path is updated. Not sure about Carthage though, since you'd have to link XCTest.

If you don't really plan on adding more features to this project though, I think it might be worth considering dropping Carthage support (users who really really still want to use Carthage can do so by specifying `0.1.4` as the version though) in favour of all the benefits SPM brings

### PR DESCRIPTION
**Pull request by henrik-dmg**
## Changes
- Added GitHub Actions to run tests when pushing to master
- Removed Xcode project file and moved source files to SPM folder structure
- Modified `Podfile` to pick up the new location of the relevant files (my workspace automatically formatted the `Podfile` using Rubocop to fit Ruby conventions, let me know if you'd like me to revert that)
- Added SPM instructions to README
- bumped version to `0.1.5`

## How to test
- either run `swift test` from within the repository folder, or
- open the package in Xcode and press `cmd` + `u`

Closes #1

### CODE REVIEW

**Comment by henrik-dmg** [comment]
@vincent-pradeilles I guess I forgot to  request a review from you, sorry about that

**Comment by vincent-pradeilles** [comment]
@henrik-dmg I've checked it out, it all looks good! Thanks!

Just one question on my side: it seems that the project (`KeyPathTesting/KeyPathTesting.xcodeproj`) can no longer be opened, because there is no `.pbxproj` inside. Do we still need to keep this `.xcodeproj` or could it also be deleted?

**Comment by henrik-dmg** [comment]
I think removing the `.xcodeproj` is not really possible with git, since it's not actually a file but a folder 😅 I guess you'll have to remove that yourself locally (git should not show any diff though)

**Comment by vincent-pradeilles** [comment]
Yeah you are totally right! I had an ignored in that directory, that's why I was still seeing it locally 😅

**Pull request merged**
